### ISSUE TITLE
.nvmrc overrides NODENV_VERSION

### ISSUE THREAD

**Issue by matt-tingen** [ouchxp/nodenv-nvmrc#5]
Without `nodenv-nvmrc`, `NODENV_VERSION` supercedes `.node-version`. It seems like `NODENV_VERSION` should also supercede `.nvmrc` when using `nodenv-nvmrc`.

Repro:
```
> echo "12.15.0" > .node-version
> nodenv version
nodenv: version `12.15.0' is not installed (set by /Users/matttingen/test/.node-version)
> NODENV_VERSION=12.14.0 nodenv version
nodenv: version `12.14.0' is not installed (set by NODENV_VERSION environment variable)
> rm .node-version
> echo "12.13.0" > .nvmrc
> nodenv version
nodenv: version `12.13.0' is not installed (set by /Users/matttingen/test/.nvmrc)
> NODENV_VERSION=12.14.0 nodenv version
nodenv: version `12.13.0' is not installed (set by /Users/matttingen/test/.nvmrc
```

**Comment by ouchxp** [comment]
Thanks for raising the issue! will look into it!

**Comment by ouchxp** [comment]
Fixed in https://github.com/ouchxp/nodenv-nvmrc/issues/5

**Comment by lumaxis** [comment]
I think this unfortunately breaks my use case 🙈
nodenv traverses the file hierarchy upwards until it finds a `.node-version` file or falls back to `~/.nodenv/version`, if that exists.
That means I can't override either a root directory's Node version or my global version via a local `.nvmrc` file because of this skip.

**Comment by ouchxp** [comment]
> I think this unfortunately breaks my use case 🙈
> nodenv traverses the file hierarchy upwards until it finds a `.node-version` file or falls back to `~/.nodenv/version`, if that exists.
> That means I can't override either a root directory's Node version or my global version via a local `.nvmrc` file because of this skip.

Hi @lumaxis , Thanks for raising the issue! Just wondering, is your issue still happening with the 1.0.4 release?

**Comment by lumaxis** [comment]
@ouchxp Yes, unfortunately still happening but for a different reason now, I think 😅 I opened #7 to track this.
